# -*- coding: utf-8 -*-
"""Introducción a Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OhYqmcuRfPp3GYdTvE_wPgz6QfxaE8IX
"""

import pandas as pd
notas = pd.read_csv("ratings.csv") 
#notas = pd.read_csv("drive/My Drive/Alura/ratings.csv")
notas.head()

notas.shape

notas.columns = ["usuarioId", "peliculaId", "nota", "momento"]
notas.head()

notas['nota']

notas['nota'].unique()

notas['nota'].value_counts()

notas['nota'].mean()

notas.nota.head()

notas.nota.plot()

notas.nota.plot(kind='hist')

print("Promedio",notas['nota'].mean())
print("Mediana",notas['nota'].median())

notas.nota.describe()

import seaborn as sns

sns.boxplot(notas.nota)

"""#Analizando las películas"""

peliculas = pd.read_csv("movies.csv") 
peliculas.head()

"""#Analizando notas de películas específicas"""

peliculas.columns = ["peliculaId", "titulo", "generos"]

notas.query("peliculaId==1")

notas.query("peliculaId==1").nota

notas.query("peliculaId==1").nota.mean()

notas.query("peliculaId==2").nota.mean()

"""# Promedio de las notas de las peliculas"""

notas.groupby("peliculaId").mean()["nota"]

promedios_por_pelicula = notas.groupby("peliculaId").mean().nota
promedios_por_pelicula.head()

promedios_por_pelicula.plot(kind = "hist")

sns.boxplot(promedios_por_pelicula)

promedios_por_pelicula.describe()

sns.distplot(promedios_por_pelicula, bins = 10)

import matplotlib.pyplot as plt
plt.hist(promedios_por_pelicula)
plt.title("Histograma de los promedios de las películas")

sns.boxplot(y=promedios_por_pelicula)

plt.figure(figsize=(5,8))

plt.figure(figsize=(5,8))
sns.boxplot(y=promedios_por_pelicula)

import pandas as pd
tmdb = pd.read_csv("tmdb_5000_movies.csv")
tmdb.head()

tmdb.original_language

tmdb.original_language.unique()

#Categorico ordinal

#primaria 
#secundaria
#universidad

#primaria >> #secundria >> #universidad

#budget --> cuantitaiva continua

#numero de votos  --> cuantitativa de intervalo

#3,5 votos 

#1 2 3 -> 1 


#Notas  0,5 5, 0,5 2,7 --> cuantitiva por intervalo #Notas  0,5 5, 0,5 2,7 --> cuantitiva por intervalo